import { MetadataRoute } from 'next';
import prisma from '@/lib/prisma';

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = 'https://soylemesibizden-core.vercel.app';

  const [listings, districts] = await Promise.all([
    prisma.listing.findMany({
      where: { status: 'ACTIVE' },
      select: { id: true, updatedAt: true },
      orderBy: { updatedAt: 'desc' },
      take: 500,
    }),
    prisma.listing.findMany({
      where: { status: 'ACTIVE', city: { not: null }, district: { not: null } },
      select: { city: true, district: true },
      distinct: ['city', 'district'],
      take: 200,
    }),
  ]);

  const staticPages: MetadataRoute.Sitemap = [
    { url: baseUrl, lastModified: new Date(), changeFrequency: 'daily', priority: 1 },
    { url: `${baseUrl}/listings`, lastModified: new Date(), changeFrequency: 'hourly', priority: 0.9 },
    { url: `${baseUrl}/search`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.8 },
    { url: `${baseUrl}/market-radar`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.7 },
    { url: `${baseUrl}/istatistikler`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/valuation`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/listings?listingType=SATILIK`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/listings?listingType=KİRALIK`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/listings?city=${encodeURIComponent('İstanbul')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/listings?city=${encodeURIComponent('Ankara')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/listings?city=${encodeURIComponent('İzmir')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/listings?city=${encodeURIComponent('Antalya')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.7 },
    { url: `${baseUrl}/sehir`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('İstanbul')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('Ankara')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('İzmir')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('Antalya')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('Bursa')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('Bodrum')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/harita`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/agents`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/hesaplama`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.65 },
    { url: `${baseUrl}/sss`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/contact`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/concierge`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.65 },
    { url: `${baseUrl}/hakkimizda`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/login`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/piyasa`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/yeni-projeler`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/kiralik`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/satilik`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/rehber`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: `${baseUrl}/rehber/ev-satin-alma`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/rehber/kiralama-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/rehber/yatirim-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/luks`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/tapu-masrafi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/fiyat-trendi`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/mahalle-analizi`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/yatirim-analizi`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/emlak-vergisi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.7 },
    { url: `${baseUrl}/portfoy`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.65 },
    { url: `${baseUrl}/kira-artis-hesaplama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/banka-kredileri`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/tum-araclar`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.8 },
    { url: `${baseUrl}/gayrimenkul-sozlugu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/rehber/satici-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/dask-hesaplayici`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.65 },
    { url: `${baseUrl}/odeme-plani`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/kira-geliri-vergisi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.7 },
    { url: `${baseUrl}/kredi-karsilastirma`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/kira-mi-satin-mi`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/pesinat-plani`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/imar-durumu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: `${baseUrl}/kentsel-donusum`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: `${baseUrl}/yabanci-gayrimenkul`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/konut-sigortasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: `${baseUrl}/butce-planlayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/kira-getiri-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/enflasyon-korumasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/miras-ve-gayrimenkul`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/kira-sozlesmesi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/tapu-devir-sureci`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/aidat-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/faiz-takip`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/yatirim-bolgesi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/emlak-komisyonu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/satilik-ev-degeri`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/belediye-hizmetleri`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: `${baseUrl}/arsa-yatirimi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/pismanlik-hakki`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/mortgage-simulatoru`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/faiz-gecmisi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/ekspertiz-raporu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/enerji-kimlik-belgesi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kat-mulkiyeti`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/yatirim-npv`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/kira-haritasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/taksitli-satis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/bolge-karsilastir`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/hisseli-tapu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/insaat-maliyeti`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/piyasa-raporu-2024`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.80 },
    { url: `${baseUrl}/stopaj-vergisi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.72 },
    { url: `${baseUrl}/deprem-riski`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/gayrimenkul-komisyoncusu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kat-karsiligi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/deger-artis-vergisi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.75 },
    { url: `${baseUrl}/sozlesme-iptal`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kira-endeksi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/konut-kredisi-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/net-gelir-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/gayrimenkul-yatirim-fonu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/sehir-planlama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/yatirim-getiri-simulatoru`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/tasinmaz-degerleme`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/kira-sozlesmesi-ornegi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/faiz-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/dolar-kuru-etkisi`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.80 },
    { url: `${baseUrl}/ortak-mulkiyet`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kentsel-donusum`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/yabanci-gayrimenkul`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/konut-sigortasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/imar-durumu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/faiz-gecmisi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/ekspertiz-raporu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/enerji-kimlik-belgesi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kat-mulkiyeti`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/arsa-yatirimi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/pismanlik-hakki`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/taksitli-satis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/hisseli-tapu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/miras-ve-gayrimenkul`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/ipotek-rehni`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/belediye-islemleri`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/depozito`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/kooperatif`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/muteahhit-secimi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/tadilat-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/tasinma-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kira-tespit-davasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/tahliye-davasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/sifir-konut`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/ev-degerleme`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/konut-ihtiyac-analizi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/kentsel-donusum-hesaplama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/satilik-ev-hazirlik`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/turizm-yatirimi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/vergi-planlama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/arsa-fiyat-hesaplama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/kira-sozlesmesi-ornegi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/emlak-piyasasi`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/satinalma-maliyeti`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/yazlik-kiralama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/ofis-kirala`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/konut-analizi`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/gayrimenkul-degerleme`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/tatil-konutu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/depo-kirala`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/butik-otel`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/kiraci-haklari`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/mal-sahibi-haklari`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/m2-fiyat-karsilastir`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/kiralik-daire-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/ev-alma-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/kira-simulatoru`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/konut-kredisi-basvuru`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/mortgage-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/pesinat-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/kira-sozlesmesi-hazirlama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/tapu-devir-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/net-kira-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/yeni-konut-projeleri`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/bolge-getiri-karsilastir`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/yabanci-yatirimci-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/deprem-sigorta-hesaplayici`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.72 },
    { url: `${baseUrl}/gayrimenkul-vergi-optimizasyon`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.75 },
    { url: `${baseUrl}/yatirim-butce-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/emlak-danismani-secme`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/fiyat-muzakere-stratejileri`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/kira-butce-planlayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/tadilat-maliyet-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/ev-tasinma-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/faiz-orani-karsilastirici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/amortisman-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/kira-tespit-davasi-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/tahliye-sureci`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/konut-kredisi-simulatoru`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/kira-deger-artisi`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/ev-satisa-hazirlama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/kredi-notu-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/ilk-ev-alma-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/aidat-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/kira-zam-tablosu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/konut-deger-tahmini`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/kentsel-donusum-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/arsa-yatirim-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/servet-birikimi-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/stopaj-vergisi-rehberi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.75 },
    { url: `${baseUrl}/konut-sigortasi-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/kira-karsiligi-birikim`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/ev-tadilat-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/gayrimenkul-yatirim-fonu-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/piyasa-raporu-2025`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/sozlesme-iptal-cayma`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/kooperatif-konut-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/mortgage-danismani`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/depozito-yonetimi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/yatirim-butce-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/gayrimenkul-vergi-optimizasyon`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.80 },
    { url: `${baseUrl}/tapu-devir-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/net-kira-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/yabanci-yatirimci-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/bolge-getiri-karsilastir`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/kira-sozlesmesi-hazirlama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/deprem-sigorta-hesaplayici`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.78 },
    { url: `${baseUrl}/kiraci-haklari`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/mal-sahibi-haklari`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/yeni-konut-projeleri`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/insaat-maliyeti`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/pesinat-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/faiz-orani-karsilastirici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/konut-kredisi-basvuru`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/kira-simulatoru`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/miras-ve-gayrimenkul`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/hisseli-tapu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/kredi-notu-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/ilk-ev-alma-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.83 },
    { url: `${baseUrl}/ev-satisa-hazirlama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/servet-birikimi-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/amortisman-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.83 },
    { url: `${baseUrl}/kentsel-donusum-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/arsa-yatirim-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/kira-karsiligi-birikim`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/konut-deger-tahmini`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/konut-sigortasi-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/stopaj-vergisi-rehberi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.78 },
    { url: `${baseUrl}/gayrimenkul-yatirim-fonu-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/kira-zam-tablosu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/piyasa-raporu-2025`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.88 },
    { url: `${baseUrl}/ev-tadilat-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/kira-deger-artisi`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/kira-butce-planlayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.83 },
    { url: `${baseUrl}/enerji-kimlik-belgesi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.76 },
    { url: `${baseUrl}/kira-artis-hakki-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.84 },
    { url: `${baseUrl}/kooperatif-konut-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.76 },
    { url: `${baseUrl}/net-bugunku-deger-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/satilik-daire-istanbul`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/kira-sozlesmesi-iptal-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/satilik-daire-ankara`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/ev-degerleme-raporu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.79 },
    { url: `${baseUrl}/kiralik-daire-istanbul`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/bina-yasi-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/tasinma-maliyet-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.79 },
    { url: `${baseUrl}/gayrimenkul-hukuk-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/kira-carpani-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.83 },
    { url: `${baseUrl}/kiralik-daire-ankara`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/satilik-villa`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.87 },
    { url: `${baseUrl}/kira-depozito-iade-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/yatirim-getiri-karsilastirici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.84 },
    { url: `${baseUrl}/satilik-arsa`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.87 },
    { url: `${baseUrl}/izmir-gayrimenkul`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/konut-kredisi-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.87 },
    { url: `${baseUrl}/antalya-gayrimenkul`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/kira-sozlesmesi-yenileme-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.77 },
    { url: `${baseUrl}/bodrum-gayrimenkul`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/metrekare-fiyat-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/bursa-gayrimenkul`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/kira-tespit-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.84 },
    { url: `${baseUrl}/satilik-daire-izmir`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/apartman-yonetimi-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.76 },
    { url: `${baseUrl}/kiralik-villa`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.87 },
    { url: `${baseUrl}/yatirim-amortisman-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.84 },
    { url: `${baseUrl}/kiralik-daire-izmir`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/tapu-iptal-davasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/fiyat-sezonu-analizi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/kira-endeks-takip`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/istanbul-avrupa-yakasi`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/konut-finansman-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/istanbul-anadolu-yakasi`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/gayrimenkul-danismanlik-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/kira-borclanma-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/konut-alim-maliyeti`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/ankara-cankaya`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/gayrimenkul-sicil-sorgulama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/izmir-karsiyaka`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/oturma-izni-gayrimenkul`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/antalya-konyaalti`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/kira-fiyat-endeksi-2024`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.82 },
    { url: `${baseUrl}/ankara-kecioren`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/konut-kredisi-puanlama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/kiralik-daire-antalya`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/kira-muzakere-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/izmir-bornova`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/ev-alim-kontrol-listesi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/istanbul-sisli`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/kira-artis-hesaplama-2025`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.88 },
    { url: `${baseUrl}/satilik-daire-bursa`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/konut-kira-orani`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.83 },
    { url: `${baseUrl}/izmir-buyuksehir`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/enerji-verimliligi-hesaplayici`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/istanbul-besiktas`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/kiralama-sureci-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/ankara-buyuksehir`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/kira-esdeger-deger`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.82 },
    { url: `${baseUrl}/istanbul-kadikoy`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/satislik-konut-deger-analizi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/istanbul-umraniye`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/gayrimenkul-vergi-rehberi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.85 },
    { url: `${baseUrl}/istanbul-maltepe`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/konut-onarim-maliyet-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/istanbul-bakirkoy`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/satilik-daire-antalya`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/ankara-etimesgut`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/kira-stopaj-vergisi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.80 },
    { url: `${baseUrl}/izmir-konak`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/tasinmaz-hukuku-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/istanbul-sariyer`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.90 },
    { url: `${baseUrl}/ev-alma-butce-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/antalya-alanya`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/kiraci-haklari-korunmasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/istanbul-pendik`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/gayrimenkul-portfoy-cesitlendirme`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
    { url: `${baseUrl}/bursa-nilufer`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/tapu-sicil-kayit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.82 },
    { url: `${baseUrl}/antalya-muratpasa`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.88 },
    { url: `${baseUrl}/insaat-ruhsati-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.80 },
  ];

  const listingPages: MetadataRoute.Sitemap = listings.map(l => ({
    url: `${baseUrl}/listing/${l.id}`,
    lastModified: l.updatedAt,
    changeFrequency: 'weekly' as const,
    priority: 0.8,
  }));

  const districtPages: MetadataRoute.Sitemap = districts
    .filter(d => d.city && d.district)
    .map(d => ({
      url: `${baseUrl}/ilce/${encodeURIComponent(d.city!)}/${encodeURIComponent(d.district!)}`,
      lastModified: new Date(),
      changeFrequency: 'daily' as const,
      priority: 0.75,
    }));

  return [...staticPages, ...listingPages, ...districtPages];
}
