import { MetadataRoute } from 'next';
import prisma from '@/lib/prisma';

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = 'https://soylemesibizden-core.vercel.app';

  const [listings, districts] = await Promise.all([
    prisma.listing.findMany({
      where: { status: 'ACTIVE' },
      select: { id: true, updatedAt: true },
      orderBy: { updatedAt: 'desc' },
      take: 500,
    }),
    prisma.listing.findMany({
      where: { status: 'ACTIVE', city: { not: null }, district: { not: null } },
      select: { city: true, district: true },
      distinct: ['city', 'district'],
      take: 200,
    }),
  ]);

  const staticPages: MetadataRoute.Sitemap = [
    { url: baseUrl, lastModified: new Date(), changeFrequency: 'daily', priority: 1 },
    { url: `${baseUrl}/listings`, lastModified: new Date(), changeFrequency: 'hourly', priority: 0.9 },
    { url: `${baseUrl}/search`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.8 },
    { url: `${baseUrl}/market-radar`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.7 },
    { url: `${baseUrl}/istatistikler`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/valuation`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/listings?listingType=SATILIK`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/listings?listingType=KİRALIK`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/listings?city=${encodeURIComponent('İstanbul')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/listings?city=${encodeURIComponent('Ankara')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/listings?city=${encodeURIComponent('İzmir')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/listings?city=${encodeURIComponent('Antalya')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.7 },
    { url: `${baseUrl}/sehir`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('İstanbul')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('Ankara')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('İzmir')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('Antalya')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('Bursa')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/sehir/${encodeURIComponent('Bodrum')}`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/harita`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/agents`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/hesaplama`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.65 },
    { url: `${baseUrl}/sss`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/contact`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/concierge`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.65 },
    { url: `${baseUrl}/hakkimizda`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/login`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/piyasa`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/yeni-projeler`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/kiralik`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/satilik`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/rehber`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: `${baseUrl}/rehber/ev-satin-alma`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/rehber/kiralama-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/rehber/yatirim-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/luks`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/tapu-masrafi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/fiyat-trendi`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/mahalle-analizi`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/yatirim-analizi`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/emlak-vergisi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.7 },
    { url: `${baseUrl}/portfoy`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.65 },
    { url: `${baseUrl}/kira-artis-hesaplama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/banka-kredileri`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/tum-araclar`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.8 },
    { url: `${baseUrl}/gayrimenkul-sozlugu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/rehber/satici-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/dask-hesaplayici`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.65 },
    { url: `${baseUrl}/odeme-plani`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/kira-geliri-vergisi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.7 },
    { url: `${baseUrl}/kredi-karsilastirma`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/kira-mi-satin-mi`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/pesinat-plani`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/imar-durumu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: `${baseUrl}/kentsel-donusum`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: `${baseUrl}/yabanci-gayrimenkul`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/konut-sigortasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: `${baseUrl}/butce-planlayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/kira-getiri-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/enflasyon-korumasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/miras-ve-gayrimenkul`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/kira-sozlesmesi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/tapu-devir-sureci`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/aidat-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/faiz-takip`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/yatirim-bolgesi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/emlak-komisyonu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/satilik-ev-degeri`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/belediye-hizmetleri`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: `${baseUrl}/arsa-yatirimi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/pismanlik-hakki`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/mortgage-simulatoru`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/faiz-gecmisi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/ekspertiz-raporu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/enerji-kimlik-belgesi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kat-mulkiyeti`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/yatirim-npv`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/kira-haritasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/taksitli-satis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/bolge-karsilastir`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/hisseli-tapu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/insaat-maliyeti`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.75 },
    { url: `${baseUrl}/piyasa-raporu-2024`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.80 },
    { url: `${baseUrl}/stopaj-vergisi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.72 },
    { url: `${baseUrl}/deprem-riski`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/gayrimenkul-komisyoncusu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kat-karsiligi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/deger-artis-vergisi`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.75 },
    { url: `${baseUrl}/sozlesme-iptal`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kira-endeksi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/konut-kredisi-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/net-gelir-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/gayrimenkul-yatirim-fonu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/sehir-planlama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/yatirim-getiri-simulatoru`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/tasinmaz-degerleme`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/kira-sozlesmesi-ornegi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/faiz-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/dolar-kuru-etkisi`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.80 },
    { url: `${baseUrl}/ortak-mulkiyet`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kentsel-donusum`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/yabanci-gayrimenkul`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/konut-sigortasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/imar-durumu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/faiz-gecmisi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/ekspertiz-raporu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/enerji-kimlik-belgesi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kat-mulkiyeti`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/arsa-yatirimi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/pismanlik-hakki`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/taksitli-satis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/hisseli-tapu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/miras-ve-gayrimenkul`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/ipotek-rehni`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/belediye-islemleri`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/depozito`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/kooperatif`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/muteahhit-secimi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/tadilat-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/tasinma-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.68 },
    { url: `${baseUrl}/kira-tespit-davasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/tahliye-davasi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/sifir-konut`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/ev-degerleme`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/konut-ihtiyac-analizi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/kentsel-donusum-hesaplama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/satilik-ev-hazirlik`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/turizm-yatirimi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/vergi-planlama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/arsa-fiyat-hesaplama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/kira-sozlesmesi-ornegi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.72 },
    { url: `${baseUrl}/emlak-piyasasi`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/satinalma-maliyeti`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/yazlik-kiralama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/ofis-kirala`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/konut-analizi`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/gayrimenkul-degerleme`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/tatil-konutu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/depo-kirala`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.70 },
    { url: `${baseUrl}/butik-otel`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/kiraci-haklari`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/mal-sahibi-haklari`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/m2-fiyat-karsilastir`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/kiralik-daire-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/ev-alma-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/kira-simulatoru`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/konut-kredisi-basvuru`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/mortgage-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/pesinat-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/kira-sozlesmesi-hazirlama`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/tapu-devir-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/net-kira-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.78 },
    { url: `${baseUrl}/yeni-konut-projeleri`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/bolge-getiri-karsilastir`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/yabanci-yatirimci-rehberi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.78 },
    { url: `${baseUrl}/deprem-sigorta-hesaplayici`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.72 },
    { url: `${baseUrl}/gayrimenkul-vergi-optimizasyon`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.75 },
    { url: `${baseUrl}/yatirim-butce-hesaplayici`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.80 },
    { url: `${baseUrl}/emlak-danismani-secme`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.73 },
    { url: `${baseUrl}/fiyat-muzakere-stratejileri`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
  ];

  const listingPages: MetadataRoute.Sitemap = listings.map(l => ({
    url: `${baseUrl}/listing/${l.id}`,
    lastModified: l.updatedAt,
    changeFrequency: 'weekly' as const,
    priority: 0.8,
  }));

  const districtPages: MetadataRoute.Sitemap = districts
    .filter(d => d.city && d.district)
    .map(d => ({
      url: `${baseUrl}/ilce/${encodeURIComponent(d.city!)}/${encodeURIComponent(d.district!)}`,
      lastModified: new Date(),
      changeFrequency: 'daily' as const,
      priority: 0.75,
    }));

  return [...staticPages, ...listingPages, ...districtPages];
}
